[package]
name = "passport-superposition-so"
version = "0.1.0"
edition = "2024"

[lib]
name = "libpassport"
edition = "2021"

[[bin]]
name = "contract"
path = "src/contract-main/main.rs"

[target.'cfg(target = "wasm-wasi-wasi")']
[[bin]]
name = "webapp"
path = "src/webapp-main/main.rs"

[target.'cfg(not(target_arch = "wasm32"))']
[[bin]]
name = "generator"
path = "src/gen-main/main.rs"

[profile.release]
codegen-units = 1
opt-level = "z"
strip = true
lto = true
debug = false
rpath = false
debug-assertions = false
incremental = false

[profile.dev]
codegen-units = 1
panic = "unwind"
opt-level = "z"
incremental = false

[dependencies]
allocator-api2 = { version = "0.2.21", default-features = false, features = ["alloc"] }
alloy-core = { version = "=0.8.20", default-features = false }
alloy-primitives = { version = "=0.8.20", default-features = false, features = ["native-keccak"] }
alloy-sol-macro-expander = "=0.8.20"
alloy-sol-macro-input = "=0.8.20"
alloy-sol-macro = { version = "=0.8.20", default-features = false }
alloy-sol-types = { version = "=0.8.20", default-features = false }
array-concat = "0.5.3"
borsh = { version = "1.5.5", default-features = false, features = ["derive"] }
const-hex = { version = "1.12.0", default-features = false }
keccak-const = "0.2.0"
lzss = { version = "0.9.1", features = ["alloc"], default-features = false }
mini-alloc = "0.7.0"
mutants = "0.0.3"
paste = "1.0.15"
sha2 = { version = "0.10.9", default-features = false }
subtle = { version = "2.6.1", default-features = false }

[dependencies.ed25519-dalek]
version = "2.1.1"
default-features = false
features = ["digest"]

[dependencies.stylus-sdk]
# This version of the SDK is considered insecure, but we can't upgrade due to stylus-core
# having a hardstuck dependency on the std.
version = "=0.8.3"
default-features = false
features = ["mini-alloc"]

[dependencies.arrayvec]
# Pointing to this repo for now since the original didn't implement Borsh properly.
version = "0.7.6"
default-features = false
features = ["borsh"]
git = "https://github.com/af-afk/arrayvec"

[dependencies.stylus-core]
version = "=0.8.3"
default-features = false

[dependencies.hashbrown]
version = "0.15.2"
default-features = false
features = ["allocator-api2", "default-hasher", "equivalent", "raw-entry"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
proptest-derive = "0.6.0"
proptest = "1.5.0"
arbitrary = { version = "1.4.1", features = ["derive"] }
alloy-primitives = { version = "=0.8.20", default-features = false, features = ["tiny-keccak", "arbitrary"] }
clap = { version = "4.5.46", features = ["derive"] }

[dev-dependencies]
const-hex = { version = "1.12.0", features = ["alloc"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.stylus-sdk]
version = "=0.8.3"
default-features = false
features = ["mini-alloc", "stylus-test"]

[features]
harness-stylus-interpreter = []
e2e-adjust-time = []
