[package]
name = "passport-superposition-so"
version = "0.1.0"
edition = "2024"

[lib]
name = "libpassport"
edition = "2021"

[[bin]]
name = "contract-solver"
path = "src/contract-solver/main.rs"

[[bin]]
name = "contract-setter"
path = "src/contract-setter/main.rs"

[[bin]]
name = "contract-admin"
path = "src/contract-admin/main.rs"

[[bin]]
name = "contract-vault"
path = "src/contract-vault/main.rs"

[[bin]]
name = "webapp"
path = "src/webapp-main/main.rs"
required-features = ["std"]

[[bin]]
name = "generator"
path = "src/gen-main/main.rs"

[profile.release]
codegen-units = 1
opt-level = "z"
strip = true
lto = true
debug = false
rpath = false
debug-assertions = false
incremental = false

[profile.dev]
codegen-units = 1
panic = "unwind"
opt-level = "z"
incremental = false

[dependencies]
allocator-api2 = { version = "0.2.21", default-features = false, features = ["alloc"] }
alloy-core = { version = "1.0.33", default-features = false }
alloy-primitives = { version = "1.0.33", default-features = false, features = ["native-keccak"] }
alloy-sol-macro-expander = "1.0.33"
alloy-sol-macro-input = "1.0.33"
alloy-sol-macro = { version = "1.0.33", default-features = false }
alloy-sol-types = { version = "1.0.33", default-features = false }
array-concat = "0.5.3"
borsh = { version = "1.5.5", default-features = false, features = ["derive"] }
const-hex = { version = "1.12.0", default-features = false }
keccak-const = "0.2.0"
lzss = { version = "0.9.1", features = ["alloc", "safe"], default-features = false }
mini-alloc = "0.7.0"
mutants = "0.0.3"
paste = "1.0.15"
sha2 = { version = "0.10.9", default-features = false }
subtle = { version = "2.6.1", default-features = false }
ed25519-dalek = { version = "2.1.1", default-features = false, features = ["digest"] }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
serde_sexpr = "0.1.0"

[dependencies.stylus-sdk]
version = "=0.10.0-beta.1"
default-features = false
features = ["mini-alloc", "reentrant"]

[dependencies.stylus-core]
version = "=0.10.0-beta.1"
default-features = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
proptest-derive = "0.6.0"
proptest = "1.5.0"
arbitrary = { version = "1.4.1", features = ["derive"] }
alloy-primitives = { version = "^1.0.1", default-features = false, features = ["tiny-keccak", "arbitrary"] }
clap = { version = "4.5.46", features = ["derive"] }
serde = "1.0.228"

[dev-dependencies]
const-hex = { version = "1.12.0", features = ["alloc"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.stylus-sdk]
version = "=0.10.0-beta.1"
default-features = false
features = ["mini-alloc", "stylus-test"]

[features]
std = []
dryrun = []
harness-stylus-interpreter = []
e2e-adjust-time = []
contract-client-gen = []
