[package]
name = "passport-superposition-so"
version = "0.1.0"
edition = "2024"

[lib]
name = "libpassport"
edition = "2021"

[[bin]]
name = "passport-superposition-so"

[dependencies]
stylus-sdk = "=0.7.0"
tiny-keccak = "2.0.2"
num-traits = { version = "0.2.19", default-features = false }
alloy-sol-types = { version = "=0.8.14", default-features = false }
alloy-sol-macro = { version = "=0.8.14", default-features = false }
alloy-core = { version = "=0.8.14", default-features = false }
alloy-primitives = { version = "=0.8.14", default-features = false }
array-concat = "0.5.3"
const-hex = { version = "1.12.0", default-features = false }
paste = "1.0.15"
rust_decimal = { version =  "1.36.0", default-features = false, features = ["maths"] }
keccak-const = "0.2.0"
alloy-sol-macro-expander = "=0.8.14"
alloy-sol-macro-input = "=0.8.14"
strum = { version = "0.26.3", default-features = false, features = ["derive"] }
mutants = "0.0.3"
borsh = { version = "1.5.5", default-features = false, features = ["derive"] }
lzss = { version = "0.9.1", features = ["alloc"], default-features = false }

[dev-dependencies]
proptest = "1.5.0"
const-hex = { version = "1.12.0", features = ["alloc"] }
rust_decimal_macros = "1.36.0"
arrayvec = "0.7.6"
map-macro = "0.3.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
proptest = "1.5.0"
getrandom = "0.2.15"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
alloy-primitives = { version = "0.7.6", features = ["getrandom"] }
rust_decimal = { version =  "1.36.0", default-features = false, features = ["maths", "proptest"] }
prettytable-rs = "0.10.0"

[profile.release]
codegen-units = 1
opt-level = "z"
strip = true
lto = true
debug = false
rpath = false
debug-assertions = false
incremental = false

[profile.dev]
codegen-units = 1
panic = "unwind"
opt-level = "z"
incremental = false

[features]
harness-stylus-interpreter = []
e2e-adjust-time = []
